### PR TITLE
Simple Web Example

### LINKED ISSUE #506: Sketches Server: Breaks when only one sketch folder
1. Create a new project with `sketches` folder
2. Add one sketch to it (e.g. `solid` from example project)
3. Open it in Hedron

It doesn't work. When compiling (?) the sketches server collapses the directory tree to one directory with `index.js` and `config.js` in there, no `solid` directory inbetween.

### PR DESCRIPTION
**Pull request by funwithtriangles**
Simple example on how to use @hedron/engine to create a web page

TODO:
- [x] all example sketches
- [x] mouse motion affects params
- [x] LFO plugin
- [x] click toggles LFO input
- [x] set pixel ratio
- [x] readme
- [x] fix `WARNING: Multiple instances of Three.js being imported.` , something to do with `LFOInput`...
- [x] ensure all build checks are passing (once other PR is merged)
- [ ] make redux devtools optional (should default to false). Getting some really bad perf issues when using theatre js

Also fixes https://github.com/nudibranchrecords/hedron/issues/506

More suggestions on how to improve things further, saving for later:
https://github.com/nudibranchrecords/hedron/issues/560

⚠️ This PR is branched from `lfo-input`, so merge that first

### CODE REVIEW

File: packages/web-example/src/main.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import { engineStore } from './engine'
+
+const lfoInputEnabledNodeId = '40fed25628e9750c'
+const saturationNodeId = 'bff7540d69fbd802'
+const sphereScaleNodeId = '0434cc9f5cc59b70'
```
Comment (cale-bradbury) [inline packages/web-example/src/main.ts:5]: oh no, doesn't feel very friendly to access the nodes in a web project

Comment (funwithtriangles) [reply packages/web-example/src/main.ts:5]: It's definitely not great! See my list of improvements for another time (https://github.com/nudibranchrecords/hedron/issues/560). We could have a nice way to select nodes. Although I do still think sometimes you'll want to grab the ID of a node from the desktop app, should be a way to copy it.
